### ISSUE TITLE
Make Profile Page UI Interactive

### ISSUE THREAD

**Issue by therealansh** [dsciiitsonepat/coeus#8]
TODO:
- [ ] Add validations to fields(email and phone)
- [ ] DOB needs to be selected from a calendar popup(if possible in the given time)
- [ ] Theming change(if possible) 
- [ ] Change the `UserEntity` accordingly

**Comment by therealansh** [comment]
DatePicker implementation can be taken from `MeetFragment`

**Comment by therealansh** [comment]
Hey @Chandra-Mauli-Sharma also if you are taking up on ProfileFragment have a look on 1st and 2nd tasks here. thanks

**Comment by Chandra-Mauli-Sharma** [comment]
@therealansh fine I am taking up this issue.
